# Railway uses Nixpacks by default, but we want to use our Dockerfile
[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "uv run fastapi run backend/main.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/problems"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
