components:
  schemas:
    CodeSubmission:
      properties:
        code:
          title: Code
          type: string
        language:
          title: Language
          type: string
      required:
      - code
      - language
      title: CodeSubmission
      type: object
    ExecutionResult:
      properties:
        error:
          anyOf:
          - type: string
          - type: 'null'
          title: Error
        output:
          title: Output
          type: string
        status:
          title: Status
          type: string
      required:
      - output
      - status
      title: ExecutionResult
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Problem:
      properties:
        description:
          title: Description
          type: string
        id:
          title: Id
          type: string
        starter_codes:
          additionalProperties:
            type: string
          title: Starter Codes
          type: object
        title:
          title: Title
          type: string
      required:
      - id
      - title
      - description
      - starter_codes
      title: Problem
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /problems:
    get:
      operationId: get_problems_problems_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Problem'
                title: Response Get Problems Problems Get
                type: array
          description: Successful Response
      summary: Get Problems
  /problems/{problem_id}:
    get:
      operationId: get_problem_problems__problem_id__get
      parameters:
      - in: path
        name: problem_id
        required: true
        schema:
          title: Problem Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Problem
  /submit:
    post:
      operationId: submit_code_submit_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeSubmission'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Submit Code

